/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define API_EXPORTED __declspec(dllexport)

#define API_EXPORTED_RELOCATABLE __declspec(dllexport)

#define CONFIG_H

#define DEPRECATED __attribute__ ((deprecated))

#define HOTSPOT __attribute__ ((hot))

#define LIBEXECDIR "c:/libexec/mmlib"

#define LOCALEDIR "c:/share/locale"

#define LOCAL_FN 

#define LT_MODULE_EXT ".dll"

#define PACKAGE_NAME "eegdev"

#define PACKAGE_STRING "eegdev 1.0"

#define PACKAGE_VERSION "1.0"

#define PKGLIBDIR "c:/lib/eegdev"

#define PKGSYSCONFDIR "c:/etc/eegdev"

#define SYSCONFDIR "c:/etc"

